version: '3.3'

services:
  web:
    container_name: BabyPOP
    image: nginx:latest
    ports:
      - '20000:80'
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ./src:/var/www/html
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: babyPOP
      MYSQL_USER: babypop
      MYSQL_PASSWORD: 2?DtQ`4%J_p:4chq
